"""UTF-8 byte tokenizer used by Spoony v0.1."""

from collections.abc import Iterable


class ByteTokenizer:
    """Convert UTF-8 text to reversible byte token IDs.

    Each token is one integer from 0 through 255. This tokenizer has no
    training phase and no unknown-token case: every Unicode string can be
    encoded as UTF-8 bytes.
    """

    vocab_size = 256

    def encode(self, text: str) -> list[int]:
        """Encode text as its UTF-8 byte values."""
        return list(text.encode("utf-8"))

    def decode(self, token_ids: Iterable[int]) -> str:
        """Decode byte token IDs back to text.

        Replacement characters are used only when generated bytes do not form
        valid UTF-8 text yet.
        """
        token_bytes = bytes(token_ids)
        return token_bytes.decode("utf-8", errors="replace")
